#ifndef PINES_H
#define PINES_h

#define PIN_MOTOR_X_PUL 47
#define PIN_MOTOR_X_DIR 46
#define PIN_MOTOR_X_EN 45
#define PIN_MOTOR_Y_PUL 44
#define PIN_MOTOR_Y_DIR 43
#define PIN_MOTOR_Y_EN 42
#define PIN_MOTOR_Z_PUL 41
#define PIN_MOTOR_Z_DIR 39
#define PIN_MOTOR_Z_EN 38

#define PIN_TECLADO_COL_1 26
#define PIN_TECLADO_COL_2 27
#define PIN_TECLADO_COL_3 28
#define PIN_TECLADO_COL_4 29

#define PIN_TECLADO_FILA_1 30
#define PIN_TECLADO_FILA_2 31
#define PIN_TECLADO_FILA_3 32
#define PIN_TECLADO_FILA_4 33

#endif